name: Update examples to latest

on:
  workflow_dispatch:

jobs:
  update-examples-pr:
    name: "Update examples PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Upgrade corepack
        shell: bash
        run: |
          npm install --force --global corepack@latest
          npm config get prefix >> $GITHUB_PATH
      - name: Run upgrade script
        run: bash scripts/update-examples-dep.sh

      - name: Make branch
        run: git checkout -b post-release-bump-examples
      - name: Create pull request
        id: pr
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: "release(turborepo): update examples to latest"
      - name: PR link
        run: echo ${{ steps.pr.outputs.html_url }}
